### ISSUE TITLE
PS2Keyboard LIB with barcode scanner

### ISSUE THREAD

**Issue by marlonvets** [yosemitebandit/PS2Keyboard#1]
Im trying to use the library with a PS/2 barcode scanner that gives its output just like a keyboard would.(http://www.karlssonrobotics.com/cart/Barcode-Reader-Scanner-Module-CCD-Camera-PS-2-Interface/) link to it. I tested the scanner on a pc and it works perfectly. When i use it on the arduino it seems to work but the arduino is either not getting an output or is not processing it properly. Any Ideas?

**Comment by yosemitebandit** [comment]
what do you mean by 'not getting an output' ?  Is it possible for you to post a code snippet?

And I should note that I think the official PS2Keyboard lib from PJRC now supports the leonardo.  It may have other fixes as well, so consider trying that.

**Comment by marlonvets** [comment]
The connector was at fault, it was not connected to the scanner. The
library and interfacing now works perfectly. Thank you.

On Sun, Apr 27, 2014 at 10:17 PM, Matt Ball notifications@github.comwrote:

> what do you mean by 'not getting an output' ? Is it possible for you to
> post a code snippet?
> 
> And I should note that I think the official PS2Keyboard lib from PJRC now
> supports the leonardo. It may have other fixes as well, so consider trying
> that.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yosemitebandit/PS2Keyboard/issues/1#issuecomment-41520004
> .

## 

A smart man makes a mistake, learns from it, and never makes that mistake
again. But a wise man finds a smart man and learns from him how to avoid
the mistake altogether.

## 

_Best regards,_
_Marlon Thompson_
_Diploma in System Administration (__NTEI__)_

_B.Sc. Electronic Engineering, Industrial Instrumentation (Pursuing) *
*University of the West Indies, Mona_
_MIGHTY VETERAN_
_571-1068_
_I came, I saw, I conquered_

This email and any files transmitted with it are confidential and intended
solely for the use of the individual(s) or entity to whom they are
addressed. If you have received this email in error please notify the
sender. This message contains confidential information and is intended only
for the individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited
